# Generated by Django 2.1.2 on 2019-12-04 09:20

import books.models.book
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('genre', models.CharField(blank=True, choices=[('sf', 'Science Fiction'), ('theatre', 'Theatre'), ('poesie', 'Poésie'), ('nouvelle', 'Nouvelle'), ('bd', 'Bande Dessinée'), ('manga', 'Manga')], max_length=150, null=True, verbose_name='Genre')),
                ('publisher', models.CharField(blank=True, max_length=150, null=True, verbose_name='Editor')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=books.models.book.upload_path_handler_cover, verbose_name='Cover')),
                ('publication_date', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year of parution')),
                ('pages', models.CharField(blank=True, max_length=5, null=True, verbose_name='Number of pages')),
                ('ISBN', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN code')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('title', 'publication_date'),
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wish', 'Whish List'), ('read', 'Read List')], default='wish', max_length=150, verbose_name='Status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Taggable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_object_type', models.CharField(choices=[('book', 'book')], max_length=20)),
                ('content_object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='books.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Author')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(to='books.Writer', verbose_name='Writers'),
        ),
    ]
