# Generated by Django 2.1.2 on 2020-01-13 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20200110_1721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reader',
            unique_together={('user', 'book')},
        ),
    ]
