# Generated by Django 2.1.2 on 2020-02-26 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200220_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_book', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
