# Generated by Django 2.1.2 on 2020-03-03 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_auto_20200226_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='book',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='readers', through='books.Reader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reader',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_book', to='books.Book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='status',
            field=models.CharField(choices=[('wish', 'Whish List'), ('read', 'Read List'), ('like', 'Like List')], default='wish', max_length=150, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
