# Generated by Django 3.0.3 on 2020-03-04 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_auto_20200304_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='readers',
            new_name='reader',
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
