# Generated by Django 3.0.3 on 2020-03-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200304_0801'),
        ('accounts', '0002_auto_20200205_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='readers',
            field=models.ManyToManyField(through='books.Reader', to='books.Book'),
        ),
    ]
